# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64b0bdfac849907ab76ee0c0f8c9d7f2d22ef0046184fd185d9dcb03535659839113d6a4434f131f9122a9397398f3ad5e4cab3b2485527da1e6711d004dece0

test:
  secret_key_base: 61ba616cf0a239a56b06dda92caa8cdf2d5dc0a5cf6554d2825d34299e786a1eb3b1175664e6f6eafba331bdb676ea10797ba0c402b6f08d178f64a1e4a0ff9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
